name: HUAWEI2

on:
    workflow_dispatch:
    schedule:
        - cron: "30 5,6 * * *"
    watch:
        types: [started]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt
    - name: Run TEXTNOW MAXIAOBO
      run: |
        python3 main.py --client textnow --username ${{ secrets.EU_USERNAME }} --password ${{ secrets.EU_PASSWORD }}
